import type { Service } from "@/types";

export const SERVICES_PT: Service[] = [
  {
    id: "business-development",
    title: "Geração de Leads B2B",
    slug: "business-development",
    shortDescription: "Pesquisa estratégica de prospects e mapeamento de decisores com base no ICP, mercado e objetivos comerciais da empresa.",
    description: "Este serviço ajuda empresas B2B a entenderem quem devem abordar, quais contas combinam com seu mercado e como organizar listas qualificadas de prospects para outreach.",
    icon: "TrendingUp",
    benefits: [
      "Pesquisa de prospects baseada no ICP",
      "Mapeamento de decisores em contas-alvo",
      "Listas mais limpas antes do outreach",
      "Contexto comercial para conversas em novos mercados",
      "Organização prática de oportunidades",
    ],
    process: [
      { step: 1, title: "Revisão do ICP", description: "Revisamos sua oferta, público, mercado e objetivos comerciais." },
      { step: 2, title: "Mapeamento de Alvos", description: "Identificamos empresas e decisores que combinam com seus critérios." },
      { step: 3, title: "Organização dos Leads", description: "Estruturamos as informações para que o outreach seja claro e focado." },
      { step: 4, title: "Revisão de Oportunidades", description: "Revisamos respostas e refinamos a direção dos alvos quando necessário." },
    ],
    metaTitle: "Geração de Leads B2B | Moreno Advisory",
    metaDescription: "Geração de leads B2B, pesquisa de prospects e mapeamento de decisores para empresas em expansão.",
  },
  {
    id: "executive-business-partnership",
    title: "LinkedIn Outreach",
    slug: "executive-business-partnership",
    shortDescription: "Abordagens humanas e personalizadas para iniciar conversas qualificadas com as pessoas certas.",
    description: "Suporte de LinkedIn outreach focado em decisores relevantes, mensagens personalizadas e follow-ups com tom humano, sem parecer automação genérica.",
    icon: "Briefcase",
    benefits: [
      "Mensagens personalizadas para LinkedIn outreach",
      "Sequências de follow-up com contexto",
      "Tom humano para primeiras conversas",
      "Acompanhamento claro das respostas",
      "Suporte para transformar interesse em próximos passos",
    ],
    process: [
      { step: 1, title: "Direção da Mensagem", description: "Clarificamos oferta, público e posicionamento antes do outreach." },
      { step: 2, title: "Escrita do Outreach", description: "Criamos mensagens personalizadas de LinkedIn e follow-ups." },
      { step: 3, title: "Acompanhamento das Conversas", description: "Organizamos respostas, interesse, objeções e próximos passos." },
      { step: 4, title: "Iteração", description: "Ajustamos mensagens com base nas respostas reais do mercado." },
    ],
    metaTitle: "LinkedIn Outreach | Moreno Advisory",
    metaDescription: "LinkedIn outreach humano para empresas B2B que precisam de conversas qualificadas com decisores certos.",
  },
  {
    id: "strategic-partnerships",
    title: "Parcerias Estratégicas",
    slug: "strategic-partnerships",
    shortDescription: "Identificação e abertura de conversas com potenciais parceiros, agências, distribuidores, canais de indicação ou oportunidades de expansão.",
    description: "Este serviço ajuda empresas a mapear caminhos de parceria e abrir conversas claras com organizações que podem se tornar parceiras, agências, distribuidoras, canais de indicação ou aliadas de expansão.",
    icon: "Handshake",
    benefits: [
      "Mapeamento de parceiros e canais",
      "Critérios claros de potencial fit",
      "Primeiras conversas personalizadas",
      "Organização das respostas de parceiros",
      "Recomendações práticas de próximos passos",
    ],
    process: [
      { step: 1, title: "Critérios de Parceria", description: "Definimos os tipos de parceiros e canais que fazem sentido para seus objetivos." },
      { step: 2, title: "Mapeamento de Mercado", description: "Identificamos organizações alinhadas aos critérios de parceria." },
      { step: 3, title: "Outreach", description: "Abrimos conversas humanas e contextualizadas com potenciais parceiros." },
      { step: 4, title: "Revisão do Pipeline", description: "Organizamos respostas, qualificamos fit e clarificamos próximos passos." },
    ],
    metaTitle: "Parcerias Estratégicas | Moreno Advisory",
    metaDescription: "Mapeie e abra conversas de parcerias B2B com agências, distribuidores, canais de indicação e parceiros de expansão.",
  },
  {
    id: "global-lead-generation",
    title: "Geração Global de Leads",
    slug: "global-lead-generation",
    shortDescription: "Suporte estruturado para identificar e organizar prospects B2B qualificados em mercados selecionados.",
    description: "A Geração Global de Leads é mantida de forma prática e focada: clarificar o ICP, mapear contas-alvo, identificar decisores e apoiar outreach organizado em mercados selecionados.",
    icon: "Globe",
    benefits: [
      "Listas de prospects baseadas no ICP",
      "Pesquisa de decisores",
      "Suporte com foco em LinkedIn outreach",
      "Dados organizados para follow-up",
      "Revisão clara de respostas e fit",
    ],
    process: [
      { step: 1, title: "Definição do ICP", description: "Perfil detalhado do seu cliente ideal em dimensões firmográficas e comportamentais." },
      { step: 2, title: "Mapeamento de Alvos", description: "Pesquisamos contas e contatos alinhados ao ICP." },
      { step: 3, title: "Suporte de Outreach", description: "Criamos mensagens humanas e follow-ups para prospects selecionados." },
      { step: 4, title: "Organização do Pipeline", description: "Acompanhamos respostas, interesse e próximos passos qualificados." },
    ],
    metaTitle: "Geração Global de Leads | Moreno Advisory",
    metaDescription: "Gere e organize prospects B2B qualificados por meio de pesquisa de ICP, mapeamento de decisores e LinkedIn outreach.",
  },
  {
    id: "international-expansion",
    title: "Expansão Internacional",
    slug: "international-expansion",
    shortDescription: "Suporte prático para empresas explorando novos mercados por meio de pesquisa, posicionamento e primeiras conversas.",
    description: "O suporte de Expansão Internacional é focado no lado comercial inicial: entender o mercado, identificar alvos relevantes e abrir conversas com contexto e sensibilidade cultural.",
    icon: "MapPin",
    benefits: [
      "Revisão de mercado e público",
      "Mapeamento inicial de contas-alvo",
      "Pesquisa de parceiros e canais",
      "Contexto localizado para outreach",
      "Organização clara dos próximos passos comerciais",
    ],
    process: [
      { step: 1, title: "Contexto de Mercado", description: "Revisamos onde sua oferta pode se encaixar e quais conversas valem ser testadas." },
      { step: 2, title: "Direção de Alvos", description: "Mapeamos empresas, parceiros e canais relevantes ao mercado." },
      { step: 3, title: "Preparação de Outreach", description: "Adaptamos a mensagem ao contexto do mercado e dos decisores." },
      { step: 4, title: "Revisão das Conversas", description: "Organizamos respostas e identificamos próximos passos práticos." },
    ],
    metaTitle: "Estratégia de Expansão Internacional | Moreno Advisory",
    metaDescription: "Explore novos mercados B2B por meio de pesquisa de prospects, mapeamento de parceiros e outreach contextualizado.",
  },
  {
    id: "business-consulting",
    title: "Consultoria Empresarial",
    slug: "business-consulting",
    shortDescription: "Assessoria prática para refinar sua oferta, direção de outreach e processo de desenvolvimento comercial.",
    description: "A Consultoria Empresarial é oferecida como suporte prático em posicionamento, abordagem de mercado, fluxo de prospecção e decisões comerciais necessárias antes do outreach.",
    icon: "BarChart3",
    benefits: [
      "Revisão clara da oferta e do mercado",
      "Recomendações comerciais práticas",
      "Suporte na priorização de públicos-alvo",
      "Desenho simples de fluxo de outreach",
      "Perspectiva estratégica founder-led",
    ],
    process: [
      { step: 1, title: "Revisão Comercial", description: "Revisamos oferta, público, outreach atual e objetivos comerciais." },
      { step: 2, title: "Mapeamento de Oportunidades", description: "Identificamos onde podem existir conversas comerciais mais claras." },
      { step: 3, title: "Recomendações", description: "Documentamos passos práticos para outreach e desenvolvimento de negócios." },
      { step: 4, title: "Suporte", description: "Ajudamos a organizar as primeiras ações e revisar a resposta do mercado." },
    ],
    metaTitle: "Consultoria Empresarial | Moreno Advisory",
    metaDescription: "Consultoria B2B prática para clareza de oferta, direção de prospecção e fluxo de desenvolvimento de negócios.",
  },
  {
    id: "commercial-intelligence",
    title: "Inteligência Comercial",
    slug: "commercial-intelligence",
    shortDescription: "Pesquisa focada de prospects, contas e decisores para apoiar melhores conversas comerciais.",
    description: "A Inteligência Comercial se concentra nas informações necessárias para um outreach melhor: quem abordar, por que essa pessoa ou empresa pode ser relevante e como iniciar a conversa com contexto.",
    icon: "Search",
    benefits: [
      "Pesquisa de prospects e contas",
      "Contexto sobre decisores",
      "Sinais de mercado e posicionamento",
      "Pesquisa de parceiros e canais",
      "Insumos para outreach mais relevante",
    ],
    process: [
      { step: 1, title: "Briefing de Pesquisa", description: "Definimos mercado, contas e perguntas importantes para o outreach." },
      { step: 2, title: "Pesquisa de Prospects", description: "Coletamos sinais relevantes sobre empresas, contatos e contexto." },
      { step: 3, title: "Síntese", description: "Transformamos a pesquisa em ângulos práticos de outreach e prioridades." },
      { step: 4, title: "Entrega", description: "Organizamos os achados para ação e follow-up." },
    ],
    metaTitle: "Inteligência Comercial | Moreno Advisory",
    metaDescription: "Inteligência comercial focada, pesquisa de prospects e mapeamento de decisores para outreach B2B.",
  },
  {
    id: "international-representation",
    title: "Representação Comercial Internacional",
    slug: "international-representation",
    shortDescription: "Suporte para representar sua empresa em conversas comerciais iniciais com prospects ou parceiros internacionais.",
    description: "A Representação Comercial Internacional é posicionada como suporte comercial inicial: abrir conversas, organizar respostas e ajudar sua empresa a se comunicar com clareza em mercados selecionados.",
    icon: "Users",
    benefits: [
      "Outreach contextualizado em mercados selecionados",
      "Comunicação clara com prospects ou parceiros",
      "Suporte na organização de respostas e próximos passos",
      "Atenção founder-led à qualidade da mensagem",
      "Perspectiva prática de B2B internacional",
    ],
    process: [
      { step: 1, title: "Briefing de Mercado", description: "Revisamos sua oferta, posicionamento e perfis de cliente-alvo." },
      { step: 2, title: "Alinhamento da Mensagem", description: "Adaptamos a linguagem de outreach ao mercado e contexto comercial." },
      { step: 3, title: "Suporte de Conversas", description: "Abrimos e organizamos conversas comerciais iniciais." },
      { step: 4, title: "Revisão de Follow-Up", description: "Acompanhamos respostas e clarificamos próximos passos." },
    ],
    metaTitle: "Representação Comercial Internacional | Moreno Advisory",
    metaDescription: "Suporte de representação B2B internacional para conversas iniciais com prospects, parceiros e mercados.",
  },
];

export const INDUSTRIES_PT = [
  {
    id: "technology",
    title: "Tecnologia & SaaS",
    description: "Ajudamos empresas de tecnologia a acelerar a adoção global e construir pipelines de vendas enterprise em mercados internacionais.",
    icon: "Cpu",
    challenges: ["Fragmentação de mercado", "Complexidade de localização", "Ciclos de compra enterprise"],
    solutions: ["Estratégia go-to-market para novas regiões", "Desenvolvimento de ecossistema de parceiros", "Programas de BD enterprise"],
  },
  {
    id: "healthcare",
    title: "Saúde & Ciências da Vida",
    description: "Navegando pela complexidade regulatória e construindo parcerias confiáveis no setor de saúde e ciências da vida.",
    icon: "HeartPulse",
    challenges: ["Conformidade regulatória", "Ciclos de venda longos", "Requisitos de credenciamento e confiança"],
    solutions: ["Estratégia de acesso ao mercado", "Identificação de distribuidores e parceiros", "Assessoria em caminhos regulatórios"],
  },
  {
    id: "finance",
    title: "Serviços Financeiros",
    description: "Apoiando inovadores de fintech e instituições financeiras tradicionais na expansão por mercados globais regulados.",
    icon: "DollarSign",
    challenges: ["Barreiras regulatórias", "Reconhecimento de marca e confiança", "Incumbentes competitivos"],
    solutions: ["Mapeamento de mercados regulatórios", "Programas de parceria institucional", "Posicionamento de marca para novos mercados"],
  },
  {
    id: "real-estate",
    title: "Mercado Imobiliário & PropTech",
    description: "Conectando incorporadoras, investidores e empresas de proptech a oportunidades transfronteiriças.",
    icon: "Building2",
    challenges: ["Complexidade de investimento cross-border", "Conhecimento de mercado local", "Gestão de relacionamento com investidores"],
    solutions: ["Prospecção internacional de investidores", "Inteligência de mercado local", "Originação e facilitação de negócios"],
  },
  {
    id: "manufacturing",
    title: "Indústria & Manufatura",
    description: "Capacitando empresas industriais a identificar novos mercados, construir redes de distribuição e otimizar a cadeia de suprimentos global.",
    icon: "Factory",
    challenges: ["Desenvolvimento de canal de distribuição", "Conformidade local", "Competitividade de preços"],
    solutions: ["Identificação e qualificação de distribuidores", "Viabilidade de entrada no mercado", "Sourcing de parceiros de supply chain"],
  },
  {
    id: "logistics",
    title: "Logística & Cadeia de Suprimentos",
    description: "Impulsionando o crescimento comercial para empresas de logística, frete e cadeia de suprimentos em corredores internacionais competitivos.",
    icon: "Truck",
    challenges: ["Desenvolvimento de rotas e corredores", "Aquisição de clientes em escala", "Parcerias operacionais"],
    solutions: ["Programas de BD por corredor", "Campanhas de prospecção de embarcadores", "Parcerias estratégicas com transportadoras"],
  },
  {
    id: "energy",
    title: "Energia & Cleantech",
    description: "Acelerando a tração comercial para empresas de energia e inovadores de cleantech em mercados emergentes e desenvolvidos.",
    icon: "Zap",
    challenges: ["Navegação em políticas e regulações", "Longos ciclos de desenvolvimento de projetos", "Acesso a capital e parceiros"],
    solutions: ["Engajamento com stakeholders e governo", "Desenvolvimento de parcerias setor privado", "Originação de pipeline de projetos"],
  },
  {
    id: "startups",
    title: "Startups & Scale-ups",
    description: "Provendo a capacidade de BD e orientação estratégica que startups de alto crescimento precisam para cruzar fronteiras com sucesso.",
    icon: "Rocket",
    challenges: ["Recursos limitados de BD", "Reconhecimento de marca em novos mercados", "Acesso a investidores e parceiros"],
    solutions: ["Liderança fracional de BD", "Programas de validação de mercado", "Introduções a investidores e aceleradoras"],
  },
  {
    id: "professional-services",
    title: "Serviços Profissionais",
    description: "Ajudando escritórios de advocacia, consultorias, contabilidade e assessorias a construir carteiras internacionais de clientes.",
    icon: "Scale",
    challenges: ["Complexidade de vendas orientada a relacionamentos", "Credibilidade geográfica", "Desenvolvimento de referências cross-border"],
    solutions: ["Programas de indicação cross-border", "Posicionamento de marca para mercados internacionais", "Programas de capacitação de BD"],
  },
];

export const STATS_PT = [
  { value: "7", suffix: "+", label: "Anos em Vendas e BD" },
  { value: "3", suffix: "", label: "Pilares de Outreach" },
];

export const VALUES_PT = [
  { icon: "Shield", title: "Integridade", description: "Operamos com padrões éticos inabaláveis, transparência e responsabilidade em cada engajamento." },
  { icon: "Eye", title: "Transparência", description: "Comunicação clara, avaliação honesta e visibilidade completa em todos os aspectos do nosso trabalho." },
  { icon: "Award", title: "Excelência", description: "Mantemos o trabalho organizado, cuidadoso e alinhado com a qualidade que cada conversa merece." },
  { icon: "Lightbulb", title: "Inovação", description: "Desafiamos constantemente abordagens convencionais e trazemos soluções criativas para problemas complexos." },
  { icon: "Globe2", title: "Perspectiva Internacional", description: "Uma visão prática a partir do Brasil para mercados selecionados e conversas B2B internacionais." },
  { icon: "Target", title: "Foco Comercial", description: "Cada engajamento é organizado em torno de alvos mais claros, melhor outreach e conversas comerciais reais." },
];
